name: branch_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: durgenious/external-workflows
          ref: branch
      - name: Greetings
        run: echo "$(<greetings.txt)"
